#!/usr/bin/env bash
# displays information about subdomains

dns_info() {
	domain="$1"
	subdomain="$2"

	if [ -z "$subdomain" ]; then
		subs=("www" "lb-01" "web-01" "web-02")
	else
		subs=("$subdomain")
	fi

	for sub in "${subs[@]}"; do
		echo -n "The subdomain $sub"
		dig $sub.$domain | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a " $4 " record and points to " $5}'
	done
}

dns_info "$1" "$2"
