#!/usr/bin/env bash
# Installing Nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html 
# sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx start
