#!/usr/bin/env bash
# bash script to ensure Nginx running, listening on port 80

# rm /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
