#!/usr/bin/env bash
# This bash script displays the content of the current directory
# In a list format Where only the part of the name after the first dash is displayed
files="$(ls)"
for f in $files
do
	echo $f | cut -d '-' -f 2
done
