#!/usr/bin/env bash
# configure nginx to run as nginx user and listen on all active IPs on port 8080

sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.config
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
